CREATE TABLE german_credit_data (
    status_of_existing_checking_account TEXT,
    duration_in_month INT,
    credit_history TEXT,
    purpose TEXT,
    credit_amount NUMERIC(10, 2),
    savings_account_bonds TEXT,
    present_employment_since TEXT,
    installment_rate_in_percentage_of_disposable_income INT,
    personal_status_and_sex TEXT,
    other_debtors_guarantors TEXT,
    present_residence_since INT,
    property TEXT,
    age_in_years INT,
    other_installment_plans TEXT,
    housing TEXT,
    number_of_existing_credits_at_this_bank INT,
    job TEXT,
    number_of_people_being_liable_to_provide_maintenance_for INT,
    telephone TEXT,
    foreign_worker TEXT,
    risk SMALLINT
);
